{ ... }:

[
  ./base.nix
  ./bootstrap.nix
  ./init-el.nix
  ./layers/completion.nix
  ./layers/git.nix
  ./layers/ivy.nix
  ./layers/latex.nix
  ./layers/nix.nix
  ./layers/nixmacs.nix
  ./layers/parens.nix
  ./packages/auctex-latexmk.nix
  ./packages/auctex.nix
  ./packages/company-nixos-options.nix
  ./packages/company.nix
  ./packages/counsel.nix
  ./packages/flycheck.nix
  ./packages/git-gutter.nix
  ./packages/ivy.nix
  ./packages/neotree.nix
  ./packages/nix-mode.nix
  ./packages/nixos-options.nix
  ./packages/powerline.nix
  ./packages/projectile.nix
  ./packages/rainbow-mode.nix
  ./packages/swiper.nix
  ./packages/yasnippet.nix
  ./settings.nix
  ./theme.nix
  ./use-package.nix
]
