language: nix
nix: 2.2.2
script: ./build-script.sh

deploy:
  provider: pages
  local_dir: ./build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  verbose: true
  on:
    branch: master